name: Testing multiple events

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  issues:
    types:
      - closed

jobs:
  multiple_events:
    runs-on: ubuntu-latest

    steps:
      - name: Testing multiple events
        run:
          echo "triggering multiple events"  
          echo "event name $GITHUB_EVENT_NAME"
          echo "github actor $GITHUB_ACTOR"
          echo "github job $GITHUB_JOB"
          echo "github ref $GITHUB_REF"
          echo "github action $GITHUB_ACTION"