name: Test schedule job every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: greeting
        run: echo " Hello World ${date}"
