name: Triggering action through webhook 

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: run a script
        run: echo "Event of type $GITHUB_EVENT_NAME"